// FORGEDIS - Detection langue par IP + traductions vitrine
// Inclure avec <script src="/lang.js"></script>

const LANGUES = {
  fr: { code: 'fr', label: 'Français',           flag: '🇫🇷' },
  en: { code: 'en', label: 'English',             flag: '🇬🇧' },
  ar: { code: 'ar', label: 'العربية',             flag: '🇸🇦', rtl: true },
  es: { code: 'es', label: 'Español',             flag: '🇪🇸' },
  pt: { code: 'pt', label: 'Português',           flag: '🇧🇷' },
  de: { code: 'de', label: 'Deutsch',             flag: '🇩🇪' },
  it: { code: 'it', label: 'Italiano',            flag: '🇮🇹' },
  dz: { code: 'dz', label: 'الدارجة',            flag: '🇩🇿', rtl: true },
};

const IP_PAYS_LANGUE = {
  FR:'fr', BE:'fr', CH:'fr', CA:'fr', LU:'fr', SN:'fr', CI:'fr', ML:'fr', CM:'fr', MG:'fr',
  GB:'en', US:'en', AU:'en', NZ:'en', IE:'en', ZA:'en', IN:'en', SG:'en', NG:'en',
  SA:'ar', AE:'ar', EG:'ar', MA:'ar', TN:'ar', LY:'ar', SD:'ar', IQ:'ar', JO:'ar', KW:'ar',
  ES:'es', MX:'es', CO:'es', AR:'es', PE:'es', VE:'es', CL:'es', EC:'es',
  PT:'pt', BR:'pt', AO:'pt', MZ:'pt',
  DE:'de', AT:'de',
  IT:'it',
  DZ:'dz',
};

let langueActuelle = 'fr';

async function detecterLangueParIP() {
  const stockee = localStorage.getItem('aria_langue');
  if (stockee && LANGUES[stockee]) { appliquerLangue(stockee); return; }
  try {
    const r = await fetch('https://ipapi.co/json/');
    const data = await r.json();
    const pays = data.country_code || 'FR';
    appliquerLangue(IP_PAYS_LANGUE[pays] || 'fr');
  } catch(e) { appliquerLangue('fr'); }
}

function appliquerLangue(code) {
  if (!LANGUES[code]) code = 'fr';
  langueActuelle = code;
  localStorage.setItem('aria_langue', code);
  document.documentElement.lang = code;
  document.documentElement.dir = LANGUES[code].rtl ? 'rtl' : 'ltr';
  document.querySelectorAll('[data-t]').forEach(el => {
    const trad = TRADUCTIONS[code] && TRADUCTIONS[code][el.getAttribute('data-t')];
    if (trad) el.innerHTML = trad;
  });
  const btn = document.getElementById('lang-btn-label');
  if (btn) btn.textContent = LANGUES[code].flag + ' ' + LANGUES[code].label;
}

function changerLangue(code) {
  appliquerLangue(code);
  const menu = document.getElementById('lang-menu');
  if (menu) menu.style.display = 'none';
}

const TRADUCTIONS = {
  fr: {
    // Nav
    'nav-produits': 'Produits',
    'nav-connexion': 'Se connecter',
    // Hero
    'hero-l1': 'Aria agit.',
    'hero-l2': 'Vous parlez.',
    'hero-mission': 'Tout le monde en difficulté devrait être aidé,',
    'hero-mission2': 'pas seulement les grands pays.',
    'hero-scroll': 'Découvrir',
    // Section produits
    'section-produits': 'Nos produits',
    'section-titre': 'Trois produits. Une seule IA.',
    'section-sous': "Aria s'adapte à qui vous êtes et à ce dont vous avez besoin.",
    // Facility
    'facility-eyebrow': 'Seniors &amp; Accessibilité',
    'facility-desc': "Aria voit votre écran, comprend ce que vous demandez, et agit à votre place. Vous parlez — elle ouvre, clique, répond, protège. Aucun logiciel à installer, aucune compétence technique requise.",
    'facility-tag1': 'Pilotage PC par la voix',
    'facility-tag2': 'Bouclier anti-arnaques',
    'facility-tag3': 'Surveillance famille',
    'facility-tag4': 'Rappels médicaments',
    'facility-essai': 'Essai gratuit 14 jours · Sans engagement',
    // Kids
    'kids-eyebrow': 'Enfants &amp; Familles',
    'kids-desc': "Du CP au BTS — devoirs, cours, langues et vie réelle. Méthode Socrate : jamais la réponse directe. Contrôle parental total inclus.",
    'kids-tag1': 'Scanner de devoirs',
    'kids-tag2': 'Vie réelle',
    'kids-tag3': 'Défis parent-enfant',
    'kids-essai': "Dès 9,99\u00a0€ · 14 jours gratuits",
    // Industrial
    'industrial-eyebrow': 'PME &amp; Entreprises',
    'industrial-desc': "Compta, RH, Achats, Service client, Logistique — un seul outil IA pour toute votre équipe. Chaque décision au bon niveau.",
    'industrial-tag1': '6 postes métier',
    'industrial-tag2': 'Hiérarchie IA',
    'industrial-tag3': 'Compatible DGFiP',
    'industrial-essai': 'Selon effectifs · 14 jours gratuits',
    // Footer
    'footer-tagline': 'Intelligence artificielle au service de ceux qui en ont besoin. France.',
    'footer-produits': 'Produits',
    'footer-legal': 'Légal',
    'footer-contact': 'Contact',
    'footer-mentions': 'Mentions légales',
    'footer-rgpd': 'RGPD',
    'footer-cgv': 'CGV',
    'footer-connexion': 'Se connecter',
  },
  en: {
    'nav-produits': 'Products',
    'nav-connexion': 'Log in',
    'hero-l1': 'Aria acts.',
    'hero-l2': 'You talk.',
    'hero-mission': 'Everyone in need deserves help,',
    'hero-mission2': 'not just wealthy nations.',
    'hero-scroll': 'Discover',
    'section-produits': 'Our products',
    'section-titre': 'Three products. One AI.',
    'section-sous': 'Aria adapts to who you are and what you need.',
    'facility-eyebrow': 'Seniors &amp; Accessibility',
    'facility-desc': 'Aria sees your screen, understands what you ask, and acts for you. You speak — she opens, clicks, replies, protects. No software to install, no technical skills required.',
    'facility-tag1': 'Voice PC control',
    'facility-tag2': 'Anti-scam shield',
    'facility-tag3': 'Family monitoring',
    'facility-tag4': 'Medication reminders',
    'facility-essai': 'Free trial 14 days · No commitment',
    'kids-eyebrow': 'Children &amp; Families',
    'kids-desc': 'From primary to college — homework, lessons, languages and real life. Socratic method: never the direct answer. Full parental control included.',
    'kids-tag1': 'Homework scanner',
    'kids-tag2': 'Real life',
    'kids-tag3': 'Parent-child challenges',
    'kids-essai': "From €9.99 · 14 days free",
    'industrial-eyebrow': 'SMEs &amp; Businesses',
    'industrial-desc': 'Accounting, HR, Purchasing, Customer service, Logistics — one AI tool for your whole team. Every decision at the right level.',
    'industrial-tag1': '6 job roles',
    'industrial-tag2': 'AI hierarchy',
    'industrial-tag3': 'DGFiP compatible',
    'industrial-essai': 'By headcount · 14 days free',
    'footer-tagline': 'Artificial intelligence for those who need it most. France.',
    'footer-produits': 'Products',
    'footer-legal': 'Legal',
    'footer-contact': 'Contact',
    'footer-mentions': 'Legal notices',
    'footer-rgpd': 'Privacy',
    'footer-cgv': 'Terms',
    'footer-connexion': 'Log in',
  },
  ar: {
    'nav-produits': 'المنتجات',
    'nav-connexion': 'تسجيل الدخول',
    'hero-l1': 'أريا تتصرف.',
    'hero-l2': 'أنت تتحدث.',
    'hero-mission': 'كل من يحتاج إلى مساعدة يستحقها،',
    'hero-mission2': 'وليس فقط الدول الكبرى.',
    'hero-scroll': 'اكتشف',
    'section-produits': 'منتجاتنا',
    'section-titre': 'ثلاثة منتجات. ذكاء اصطناعي واحد.',
    'section-sous': 'أريا تتكيف مع هويتك واحتياجاتك.',
    'facility-eyebrow': 'كبار السن وإمكانية الوصول',
    'facility-desc': 'أريا ترى شاشتك وتفهم طلبك وتتصرف بدلاً عنك. أنت تتحدث — هي تفتح وتنقر وترد وتحمي. لا برامج للتثبيت، لا مهارات تقنية مطلوبة.',
    'facility-tag1': 'التحكم بالحاسوب بالصوت',
    'facility-tag2': 'درع ضد الاحتيال',
    'facility-tag3': 'مراقبة الأسرة',
    'facility-tag4': 'تذكيرات الدواء',
    'facility-essai': 'تجربة مجانية 14 يوم · بدون التزام',
    'kids-eyebrow': 'الأطفال والعائلات',
    'kids-desc': 'من الابتدائي إلى الجامعة — واجبات، دروس، لغات وحياة واقعية. طريقة سقراط: لا إجابة مباشرة أبداً. رقابة أولياء الأمور الكاملة مشمولة.',
    'kids-tag1': 'ماسح الواجبات',
    'kids-tag2': 'الحياة الواقعية',
    'kids-tag3': 'تحديات الوالدين والطفل',
    'kids-essai': 'من 9.99€ · 14 يوم مجاني',
    'industrial-eyebrow': 'المؤسسات والشركات',
    'industrial-desc': 'محاسبة، موارد بشرية، مشتريات، خدمة العملاء، لوجستيك — أداة ذكاء اصطناعي واحدة لفريقك بأكمله.',
    'industrial-tag1': '6 أدوار وظيفية',
    'industrial-tag2': 'تسلسل هرمي بالذكاء الاصطناعي',
    'industrial-tag3': 'متوافق مع DGFiP',
    'industrial-essai': 'حسب عدد الموظفين · 14 يوم مجاني',
    'footer-tagline': 'الذكاء الاصطناعي في خدمة من يحتاجه. فرنسا.',
    'footer-produits': 'المنتجات',
    'footer-legal': 'قانوني',
    'footer-contact': 'اتصال',
    'footer-mentions': 'إشارات قانونية',
    'footer-rgpd': 'الخصوصية',
    'footer-cgv': 'الشروط',
    'footer-connexion': 'تسجيل الدخول',
  },
  es: {
    'nav-produits': 'Productos',
    'nav-connexion': 'Iniciar sesión',
    'hero-l1': 'Aria actúa.',
    'hero-l2': 'Tú hablas.',
    'hero-mission': 'Todo el mundo con dificultades merece ayuda,',
    'hero-mission2': 'no solo los países ricos.',
    'hero-scroll': 'Descubrir',
    'section-produits': 'Nuestros productos',
    'section-titre': 'Tres productos. Una sola IA.',
    'section-sous': 'Aria se adapta a quién eres y a lo que necesitas.',
    'facility-eyebrow': 'Mayores &amp; Accesibilidad',
    'facility-desc': 'Aria ve tu pantalla, entiende lo que pides y actúa por ti. Tú hablas — ella abre, hace clic, responde, protege. Sin software que instalar, sin conocimientos técnicos.',
    'facility-tag1': 'Control PC por voz',
    'facility-tag2': 'Escudo anti-estafas',
    'facility-tag3': 'Vigilancia familiar',
    'facility-tag4': 'Recordatorios de medicamentos',
    'facility-essai': 'Prueba gratuita 14 días · Sin compromiso',
    'kids-eyebrow': 'Niños &amp; Familias',
    'kids-desc': 'De primaria a universidad — deberes, clases, idiomas y vida real. Método socrático: nunca la respuesta directa. Control parental total incluido.',
    'kids-tag1': 'Escáner de deberes',
    'kids-tag2': 'Vida real',
    'kids-tag3': 'Retos padre-hijo',
    'kids-essai': 'Desde 9,99€ · 14 días gratis',
    'industrial-eyebrow': 'PYMEs &amp; Empresas',
    'industrial-desc': 'Contabilidad, RRHH, Compras, Atención al cliente, Logística — una sola herramienta IA para todo tu equipo.',
    'industrial-tag1': '6 puestos de trabajo',
    'industrial-tag2': 'Jerarquía IA',
    'industrial-tag3': 'Compatible DGFiP',
    'industrial-essai': 'Según plantilla · 14 días gratis',
    'footer-tagline': 'Inteligencia artificial al servicio de quienes la necesitan. Francia.',
    'footer-produits': 'Productos',
    'footer-legal': 'Legal',
    'footer-contact': 'Contacto',
    'footer-mentions': 'Aviso legal',
    'footer-rgpd': 'Privacidad',
    'footer-cgv': 'Términos',
    'footer-connexion': 'Iniciar sesión',
  },
  pt: {
    'nav-produits': 'Produtos',
    'nav-connexion': 'Entrar',
    'hero-l1': 'Aria age.',
    'hero-l2': 'Você fala.',
    'hero-mission': 'Todo mundo com dificuldades merece ajuda,',
    'hero-mission2': 'não apenas os países ricos.',
    'hero-scroll': 'Descobrir',
    'section-produits': 'Nossos produtos',
    'section-titre': 'Três produtos. Uma só IA.',
    'section-sous': 'Aria se adapta a quem você é e ao que você precisa.',
    'facility-eyebrow': 'Idosos &amp; Acessibilidade',
    'facility-desc': 'Aria vê a sua tela, entende o que você pede e age por você. Você fala — ela abre, clica, responde, protege. Sem software para instalar, sem habilidades técnicas.',
    'facility-tag1': 'Controlo do PC por voz',
    'facility-tag2': 'Escudo anti-fraude',
    'facility-tag3': 'Vigilância familiar',
    'facility-tag4': 'Lembretes de medicamentos',
    'facility-essai': 'Teste grátis 14 dias · Sem compromisso',
    'kids-eyebrow': 'Crianças &amp; Famílias',
    'kids-desc': 'Do ensino básico ao superior — tarefas, aulas, línguas e vida real. Método socrático: nunca a resposta direta. Controlo parental total incluído.',
    'kids-tag1': 'Scanner de trabalhos de casa',
    'kids-tag2': 'Vida real',
    'kids-tag3': 'Desafios pais-filho',
    'kids-essai': 'A partir de 9,99€ · 14 dias grátis',
    'industrial-eyebrow': 'PME &amp; Empresas',
    'industrial-desc': 'Contabilidade, RH, Compras, Atendimento ao cliente, Logística — uma única ferramenta IA para toda a sua equipa.',
    'industrial-tag1': '6 funções profissionais',
    'industrial-tag2': 'Hierarquia IA',
    'industrial-tag3': 'Compatível DGFiP',
    'industrial-essai': 'Por número de funcionários · 14 dias grátis',
    'footer-tagline': 'Inteligência artificial ao serviço de quem precisa. França.',
    'footer-produits': 'Produtos',
    'footer-legal': 'Legal',
    'footer-contact': 'Contato',
    'footer-mentions': 'Avisos legais',
    'footer-rgpd': 'Privacidade',
    'footer-cgv': 'Termos',
    'footer-connexion': 'Entrar',
  },
  de: {
    'nav-produits': 'Produkte',
    'nav-connexion': 'Anmelden',
    'hero-l1': 'Aria handelt.',
    'hero-l2': 'Sie sprechen.',
    'hero-mission': 'Jeder in Not verdient Hilfe,',
    'hero-mission2': 'nicht nur reiche Länder.',
    'hero-scroll': 'Entdecken',
    'section-produits': 'Unsere Produkte',
    'section-titre': 'Drei Produkte. Eine KI.',
    'section-sous': 'Aria passt sich an, wer Sie sind und was Sie brauchen.',
    'facility-eyebrow': 'Senioren &amp; Barrierefreiheit',
    'facility-desc': 'Aria sieht Ihren Bildschirm, versteht Ihre Anfragen und handelt für Sie. Sie sprechen — sie öffnet, klickt, antwortet, schützt. Keine Software zu installieren, keine technischen Kenntnisse erforderlich.',
    'facility-tag1': 'PC-Steuerung per Sprache',
    'facility-tag2': 'Anti-Betrugs-Schild',
    'facility-tag3': 'Familienüberwachung',
    'facility-tag4': 'Medikamentenerinnerungen',
    'facility-essai': 'Kostenlose Testversion 14 Tage · Keine Bindung',
    'kids-eyebrow': 'Kinder &amp; Familien',
    'kids-desc': 'Von der Grundschule bis zum Abitur — Hausaufgaben, Unterricht, Sprachen und echtes Leben. Sokratische Methode: nie die direkte Antwort. Volle elterliche Kontrolle inklusive.',
    'kids-tag1': 'Hausaufgaben-Scanner',
    'kids-tag2': 'Echtes Leben',
    'kids-tag3': 'Eltern-Kind-Herausforderungen',
    'kids-essai': 'Ab 9,99€ · 14 Tage kostenlos',
    'industrial-eyebrow': 'KMU &amp; Unternehmen',
    'industrial-desc': 'Buchhaltung, HR, Einkauf, Kundendienst, Logistik — ein einziges KI-Tool für Ihr gesamtes Team.',
    'industrial-tag1': '6 Berufsrollen',
    'industrial-tag2': 'KI-Hierarchie',
    'industrial-tag3': 'DGFiP-kompatibel',
    'industrial-essai': 'Nach Mitarbeiterzahl · 14 Tage kostenlos',
    'footer-tagline': 'Künstliche Intelligenz für alle, die sie brauchen. Frankreich.',
    'footer-produits': 'Produkte',
    'footer-legal': 'Rechtliches',
    'footer-contact': 'Kontakt',
    'footer-mentions': 'Impressum',
    'footer-rgpd': 'Datenschutz',
    'footer-cgv': 'AGB',
    'footer-connexion': 'Anmelden',
  },
  it: {
    'nav-produits': 'Prodotti',
    'nav-connexion': 'Accedi',
    'hero-l1': 'Aria agisce.',
    'hero-l2': 'Tu parli.',
    'hero-mission': 'Tutti coloro che hanno difficoltà meritano aiuto,',
    'hero-mission2': 'non solo i paesi ricchi.',
    'hero-scroll': 'Scoprire',
    'section-produits': 'I nostri prodotti',
    'section-titre': 'Tre prodotti. Una sola IA.',
    'section-sous': 'Aria si adatta a chi sei e a ciò di cui hai bisogno.',
    'facility-eyebrow': 'Anziani &amp; Accessibilità',
    'facility-desc': "Aria vede il tuo schermo, capisce cosa chiedi e agisce al posto tuo. Tu parli — lei apre, clicca, risponde, protegge. Nessun software da installare, nessuna competenza tecnica richiesta.",
    'facility-tag1': 'Controllo PC tramite voce',
    'facility-tag2': 'Scudo anti-truffe',
    'facility-tag3': 'Sorveglianza familiare',
    'facility-tag4': 'Promemoria farmaci',
    'facility-essai': 'Prova gratuita 14 giorni · Senza impegno',
    'kids-eyebrow': 'Bambini &amp; Famiglie',
    'kids-desc': "Dalle elementari all'università — compiti, lezioni, lingue e vita reale. Metodo socratico: mai la risposta diretta. Controllo parentale totale incluso.",
    'kids-tag1': 'Scanner compiti',
    'kids-tag2': 'Vita reale',
    'kids-tag3': 'Sfide genitore-figlio',
    'kids-essai': 'Da 9,99€ · 14 giorni gratis',
    'industrial-eyebrow': 'PMI &amp; Aziende',
    'industrial-desc': "Contabilità, HR, Acquisti, Servizio clienti, Logistica — un solo strumento IA per tutto il tuo team.",
    'industrial-tag1': '6 ruoli professionali',
    'industrial-tag2': 'Gerarchia IA',
    'industrial-tag3': 'Compatibile DGFiP',
    'industrial-essai': 'In base al numero di dipendenti · 14 giorni gratis',
    'footer-tagline': "Intelligenza artificiale al servizio di chi ne ha bisogno. Francia.",
    'footer-produits': 'Prodotti',
    'footer-legal': 'Legale',
    'footer-contact': 'Contatto',
    'footer-mentions': 'Note legali',
    'footer-rgpd': 'Privacy',
    'footer-cgv': 'Termini',
    'footer-connexion': 'Accedi',
  },
  dz: {
    'nav-produits': 'لمنتجات',
    'nav-connexion': 'دخل',
    'hero-l1': 'أريا تخدم.',
    'hero-l2': 'نتكلم أنت.',
    'hero-mission': 'كل واحد محتاج يستاهل المساعدة،',
    'hero-mission2': 'مش غير البلدان الكبيرة.',
    'hero-scroll': 'اكتشف',
    'section-produits': 'منتجاتنا',
    'section-titre': 'ثلاث منتجات. ذكاء اصطناعي واحد.',
    'section-sous': 'أريا تتكيف معاك وماك محتاجو.',
    'facility-eyebrow': 'كبار السن وإمكانية الوصول',
    'facility-desc': 'أريا تشوف شاشتك، تفهم طلبك، وتخدم عليك. تتكلم — هي تفتح، تكليك، تجاوب، تحمي. ما كاش برنامج تنصبو، ما كاش مهارات تقنية.',
    'facility-tag1': 'التحكم بالكمبيوتر بالصوت',
    'facility-tag2': 'حماية من النصب',
    'facility-tag3': 'مراقبة العائلة',
    'facility-tag4': 'تذكير الدواء',
    'facility-essai': 'تجربة مجانية 14 يوم · بلا التزام',
    'kids-eyebrow': 'الأطفال والعائلات',
    'kids-desc': 'من الابتدائي للجامعة — واجبات، دروس، لغات وحياة حقيقية. طريقة سقراط: ما عمر الجواب المباشر. مراقبة الوالدين الكاملة مشمولة.',
    'kids-tag1': 'ماسح الواجبات',
    'kids-tag2': 'الحياة الحقيقية',
    'kids-tag3': 'تحديات الوالدين والطفل',
    'kids-essai': 'من 9.99€ · 14 يوم مجاني',
    'industrial-eyebrow': 'المؤسسات والشركات',
    'industrial-desc': 'محاسبة، موارد بشرية، مشتريات، خدمة العملاء، لوجستيك — أداة ذكاء اصطناعي واحدة لكل فريقك.',
    'industrial-tag1': '6 أدوار مهنية',
    'industrial-tag2': 'هرمية بالذكاء الاصطناعي',
    'industrial-tag3': 'متوافق مع DGFiP',
    'industrial-essai': 'حسب عدد الموظفين · 14 يوم مجاني',
    'footer-tagline': 'الذكاء الاصطناعي في خدمة اللي يحتاجه. فرنسا.',
    'footer-produits': 'لمنتجات',
    'footer-legal': 'قانوني',
    'footer-contact': 'تواصل',
    'footer-mentions': 'معلومات قانونية',
    'footer-rgpd': 'خصوصية',
    'footer-cgv': 'شروط',
    'footer-connexion': 'دخل',
  },
};

document.addEventListener('DOMContentLoaded', detecterLangueParIP);
window.AriaLang = { changerLangue, appliquerLangue, TRADUCTIONS, LANGUES, get langue() { return langueActuelle; } };
